apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: vote-prod

# Scaling for high traffic in Production
namespace: vote-prod
namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: vote
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Service
      name: vote
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31010
  - target:
      kind: Service
      name: result
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31011
  - target:
      kind: Ingress
      name: voting-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vote.local
      - op: replace
        path: /spec/rules/1/host
        value: result.local